### ISSUE TITLE
HomematicIP - New sensor HmIP-DLS

### ISSUE THREAD

**Issue by ToTanne** [danielperna84/pydevccu#17]
According to this entry:
https://community.home-assistant.io/t/homematicip-new-sensor-hmip-dls/357175/5
I let  the phytonscript run and attached  the result as a ZIP to this
[HmIP-DLS-descriptions.zip](https://github.com/danielperna84/pydevccu/files/7951340/HmIP-DLS-descriptions.zip).

Many thanks for your help!
Toby

**Comment by danielperna84** [comment]
That data way already provided earlier and added to the repository with [this](https://github.com/danielperna84/pydevccu/commit/e37f1c9c2c93e17795d5444b741babdc83648226) commit. Thanks though for contributing. 👍

By the way, check out the new integration we're working on. The device will be working with it already probably. Here's the repository for the custom component: https://github.com/danielperna84/custom_homematic
