### ISSUE TITLE
HM-LC-RGBW-WM support

### ISSUE THREAD

**Issue by Hypnos3** [danielperna84/pydevccu#25]
Please support Homematic "HM-LC-RGBW-WM" Device. (from [here ](https://github.com/danielperna84/hahomematic/issues/408))
[HM-LC-RGBW-WM.zip](https://github.com/danielperna84/pydevccu/files/8524911/HM-LC-RGBW-WM.zip)

Many thanks for your help!
Toby

**Comment by danielperna84** [comment]
@SukramJ 
FYI added with 0e93b94364727b99e8db974d68a2043fba17ebaf
