### ISSUE TITLE
Add support for ALPHA-IP-RBG

### ISSUE THREAD

**Issue by Siumba** [danielperna84/pydevccu#29]
Attached the exported files from the device definitions service.

Please add support for ALPHA-IP-RBG.
[ALPHA-IP-RBG.zip](https://github.com/danielperna84/pydevccu/files/9732489/ALPHA-IP-RBG.zip)

**Comment by SukramJ** [comment]
Looks like something is broken in the paramset description.

Please do the following:
1. Use the HA service homematicip_local.clear_cache and restart HA.
2. Retry the export. The paramset description should be multiple kilo bytes big.

**Comment by Siumba** [comment]
My bad, I think it was a cache issue. Attached a new .zip with both files.
[ALPHA-IP-RBG.zip](https://github.com/danielperna84/pydevccu/files/9732834/ALPHA-IP-RBG.zip)

**Comment by SukramJ** [comment]
Looks good.
