### ISSUE TITLE
HmIP-FWI

### ISSUE THREAD

**Issue by Bastian007** [danielperna84/pydevccu#46]
As recommended [here](https://github.com/danielperna84/hahomematic/discussions/1285#discussioncomment-7495184), I'm providing the two files for HmIP-FWI: 
>>files deleted

How the device looks in CCU3:
![FWI_CH0_2023-11-07_13-10-03](https://github.com/danielperna84/pydevccu/assets/12425311/50f6e886-67ed-4198-bbad-f0108db08a1d)
![FWI_CH1-8_2023-11-07_13-11-12](https://github.com/danielperna84/pydevccu/assets/12425311/db73bbff-f051-4ef2-a94d-3d279c0e1f10)
![FWI_CH_9-13_2023-11-07_13-12-08](https://github.com/danielperna84/pydevccu/assets/12425311/b0f98a51-9a9b-40fe-b23b-cf5f9dcddb2a)

**Comment by SukramJ** [comment]
These are the wrong files (from the cache folder). There are extra subfolders with export_device_description and extra_paramset_description.

**Comment by Bastian007** [comment]
So actually I cannot see those subfolders:
<img width="829" alt="image" src="https://github.com/danielperna84/pydevccu/assets/12425311/44c77e1e-4f38-4512-a2e4-b8d7ca01d9be">

I am using Homematic(IP) Local 1.48.0. Any idea?

**Comment by SukramJ** [comment]
Did you execute the service?

**Comment by Bastian007** [comment]
Well, it makes sense to read the entire page... Thanks!

Please find now the correct files attached:
[HmIP-FWI_export_device_descriptions.json](https://github.com/danielperna84/pydevccu/files/13298879/HmIP-FWI_export_device_descriptions.json)
[HmIP-FWI_export_paramset_descriptions.json](https://github.com/danielperna84/pydevccu/files/13298880/HmIP-FWI_export_paramset_descriptions.json)

**Comment by Bastian007** [comment]
@SukramJ Should I detect any difference with version 1.49.0 after HmIP-FWI has been added?

**Comment by SukramJ** [comment]
No, and everything should already be answered [here](https://github.com/danielperna84/hahomematic/discussions/1285#discussioncomment-7495184).
HmIP-FWI is just a bunch of sensors.
