### ISSUE TITLE
Repositories übertragen ???

### ISSUE THREAD

**Issue by SukramJ** [danielperna84/pydevccu#56]
Moin Daniel,
 
ich meine gelesen zu haben, das Du selber Homematic nicht mehr einsetzt, aber ich kann den entsprechenden Post nicht mehr finden.
 
Die Frage, die sich nicht nur deshalb seit einiger Zeit stellt ist, ob Du Interesse daran hast die Homematic Repositories auf mich zu übertragen. 
 
Im speziellen denke ich in einem ersten Schritt an hahomematic und pydevccu. Aktuell hakt es mit neuen Releases für pydevccu.
 
Eine Übertragung von custom_homematic wäre mir aktuell noch zu heikel, da ich nicht weiß, ob HACS die Weiterleitung sauber unterstützt.
 
Was denkst Du?
 
Gruß
Markus

**Comment by danielperna84** [comment]
Klar, können wir machen. Und es stimmt, ich hab kein HomeMatic mehr. Würde also absolut Sinn ergeben. Ich schaue heute Abend / Nacht mal, welche Optionen GitHub mir da bietet. Und bei pypi (falls du dort noch hochlädtst) kann ich dich zumindest als Maintainer oder so hinzufügen (falls ich das nicht schon getan habe). Ob man da den Owner wechseln kann schaue ich dann auch mal. 👍

**Comment by SukramJ** [comment]
Das hört sich gut an. Ich hab meine Forks gelöscht, so das ich empfangen kann.
Ich glaube bei PyPi kann man auch transferieren.

**Comment by danielperna84** [comment]
So, für dieses Repo + hahomematic hab ich den Transfer angestoßen. Bei custom_homematic kam mir noch der Gedanke, dass ja einige Tutorials auch auf das Repo verweisen. Da wäre also auch die Frage, wohin ein Link zur bisherigen URL die User dann führt.

**Comment by SukramJ** [comment]
Step 1 hat schon mal geklappt.

> Da wäre also auch die Frage, wohin ein Link zur bisherigen URL die User dann führt.

Aktuell werden Links die gegen `danielperna84/hahomematic` gehen automatisch auf `SukramJ/hahomematic` umgeleitet.
Ich gehe davon aus, das das für `custom_homematic` auch der Fall sein wird.

Von mir aus können wir also auch `custom_homematic` transferieren. 

Ich werden im Nachgang mal diverse Leute anschreiben, um den Link in Dokus/Videos zu aktualisieren, bzw eine allgemeine Info erstellen, wie man den Link in HACS ändert.

Möchtest du noch weiterhin als Maintainer/Contributor bei denProjekten mit eingetragen sein, oder soll ich dich da rausnehmen?

**Comment by danielperna84** [comment]
Als Contributor schon. Ist ja nicht so, als hätte ich nix beigetragen. Maintainer muss ich nicht sein. Ich mach' ja jetzt nix mehr.

**Comment by SukramJ** [comment]
Ich will dich ja nicht rauskicken.
Es geht nur um die Projektberechtigungen.

**Comment by SukramJ** [comment]
Also noch mal konkret:
- Als Author bleibst du in den Projektbeschreibungen erhalten 
- Die Urls werden alle geändert

Willst Du Betreuer bei PyPi bleiben? Wenn ich dich richtig verstanden habe dann NEIN.
Willst Du Collaborator bei GitHub bleiben? Wenn ich dich richtig verstanden habe dann NEIN.

**Comment by danielperna84** [comment]
Ja, nimm mich raus. 👍

**Comment by SukramJ** [comment]
OK, hab ich gemacht.

Dann übertrage bitte als nächstes `custom_homematic`.

**Comment by danielperna84** [comment]
Erledigt

**Comment by SukramJ** [comment]
Super und vielen Dank.

Und abschliessend noch mal ein grosses Dankschön für die tolle Projektidee und die sehr gute Vorarbeit, ohne die ich mich nicht an eine CCU Integration gewagt hätte.

Ich wünsche dir alles Gute, ein frohes Fest und einen guten Rutsch ins neue Jahr.

VG

**Comment by akentner-cp** [comment]
Ich finde es sehr erfreulich, dass das Projekt weitergeführt wird. Danke hier schon mal @SukramJ 

Auch dass die Kommunikation hierzu sehr transparent geführt wird, finde ich sehr erfrischend. Ich finde das so toll, dass ich das hier mal herausstellen wollte.

Bleibt mir nur noch @danielperna84 hier für seine hervorragende Arbeit die letzten Jahre Lob auszusprechen. Vielen Dank hierfür, du hast viele Probleme der Original-Integration gelöst. Simply Lovely.

Ich wünsche euch alles Gute, besinnliche Feiertage und einen guten Start ins neue Jahr 🎄 🎆
